### ISSUE TITLE
Project Peer Review by James Zhang

### ISSUE THREAD

**Issue by Santiagoooooo** [SebasRSoler/webtech-project#3]
Hi,
Love your website and great job!

Technical issues/bugs:
1. "Watch Game" button doesn't link to anything. 
2. "submit" button on the Blog page doesn't work.
Suggestion:
1. More css will make your website more attractive.
2. Adjust the overall layout and font-size on the homepage. 

Thanks,
James

**Comment by SebasRSoler** [comment]
Hello, 
Thank you for your advice and comments. I will work on all the content and technical issues. 
Thank you!
