### ISSUE TITLE
Project Peer Review by Elina Hsueh

### ISSUE THREAD

**Issue by ehsueh2** [SebasRSoler/webtech-project#4]
**Technical:**

1. Contact us page: Form is missing `"Action"` HTML attribute and `method="Post"` HTML attributes in HTML. The form defaults to `method = "GET"`, which runs into issue of text being too long in the URL when user submits form. See [https://www.w3schools.com/tags/ref_httpmethods.asp](url).

2. Top navigation and bottom navigation banner are not consistent. Top banner is missing Latest News and Contact Us.

**Content:**
1. Game Schedule page: 2019-20 Season and Regular Season forms are sized to content but not aligned. For aesthetics, they should be aligned to same size on page.

2. Using smaller heading, like `h2` tags, for subheadings on Team Roster page.

**Comment by SebasRSoler** [comment]
Thank you for your advice and help. I really appreciate the link for additional help!
