### ISSUE TITLE
Project Peer review by Oliver Yang

### ISSUE THREAD

**Issue by Oliver-886** [SebasRSoler/webtech-project#5]
I think your website is rich with contents. You have a lot of good photos and the overall layout is fantastic.

Technical:
Add "title" to your images 
Use class for h1 in your roaster page so you can center it or edit it in CSS in the future

Content:
Use CSS to style the Navigation bar 
apply a consistent theme for your page 
add appropriate margin to your about page so it is easier to read 
add a search button to the index_page

**Comment by SebasRSoler** [comment]
Thank you for your advice and tips! I will work on my content and technical issues. Thank you
